name: Trigger NotOften
on:
  push:
    branches:
      - often-test
    paths:
      - .github/workflows/do-not-trigger-to-often.yml
      - src/often.js

  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          echo "Running from ${{ github.workflow }}"
          
      - uses: actions/github-script@v5.0.0
        with:
          # The script to run
          script: |
            const owner = "rajbos"
            const repo = "demo-actions"
            const workflow = "${{ github.workflow }}"

            const script = require('./src/often.js')
            const test = await script({github, context, owner, repo, workflow})
            
            console.log("Done")            
