name: Trigger NotOften
on:
  push:
    paths:
      - .github/workflows/do-not-trigger-to-often.yml
      - src/often.js

  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - env:
          workflow_context: ${{ toJSON(github) }}
        run: |
          echo "Running from ${{ github.workflow }}"
          echo "Context: $workflow_context"
          
      - uses: actions/github-script@v6
        with:
          # The script to run
          script: |
            const owner = "rajbos"
            const repo = "demo-actions"
            const workflow = "${{ github.workflow }}"

            const script = require('./src/often.js')
            const test = script({github, context, owner, repo, workflow})
            
            console.log("Done")            
