name: Trigger NotOften
on:
  push:
    branches:
      - often-test
    paths:
      - .github/workflows/do-not-trigger-to-often.yml
      - src/often.js

  workflow_dispatch:    

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - env:
          github_context: ${{ toJson(github) }}
        run: |
          echo "Running from ${{ github.workflow }} with ${{ github.run_id }}"
          echo "github_context: $github_context"
      - run: |
          echo "github.workflow_ref: ${{ github.workflow_ref }}"
          
      - uses: actions/github-script@v5.0.0
        with:
          # The script to run
          script: |
            const owner = "rajbos"
            const repo = "demo-actions"
            
            const run_id = "${{ github.run_id }}"

            let workflow = "${{ github.workflow }}" // is the name of the workflow, and not the filename or actual id
            workflow = "${{ github.workflow_ref }}" // is the full ref for the workflow, which is a known path

            const script = require('./src/often.js')
            const test = await script({github, owner, repo, workflow, run_id})
            
            await new Promise(r => setTimeout(r, 6000))
            console.log("Done")            
